name: news_reader
description: A Flutter news reader application with dynamic theming and offline support.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # State management
  provider: ^6.1.1
  
  # Networking
  dio: ^5.3.3
  connectivity_plus: ^5.0.1
  
  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  
  # Dependency injection
  get_it: ^7.6.4
  
  # JSON serialization
  json_annotation: ^4.8.1
  
  # UI
  cached_network_image: ^3.3.0
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  google_fonts: ^6.2.1  # Added Google Fonts
  
  # Utilities
  intl: ^0.18.1
  logger: ^2.0.2+1
  url_launcher: ^6.2.1
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  # Fonts section can be removed if using google_fonts
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700